DROP DATABASE IF EXISTS coderedemp;
CREATE DATABASE IF NOT EXISTS coderedemp;

USE coderedemp;

DROP TABLE IF EXISTS PROMOIDS;
DROP TABLE IF EXISTS ARTISTS;
DROP TABLE IF EXISTS ALBUMS;
DROP TABLE IF EXISTS CODES;

CREATE TABLE PROMOIDS ( 
  ID INT NOT NULL AUTO_INCREMENT, 
  PID INT NOT NULL,
  NAME VARCHAR(50),
  PRIMARY KEY(ID)
) ;


CREATE TABLE ARTISTS ( 
  ID INT NOT NULL AUTO_INCREMENT, 
  NAME VARCHAR(50),
  PRIMARY KEY(ID)
) ;
  

CREATE TABLE ALBUMS (
    ID INT NOT NULL AUTO_INCREMENT,
    PIGID INT NOT NULL UNIQUE,
    NAME VARCHAR(50),
    ARTIST_ID INT NOT NULL,
    PROMO_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ID),
    FOREIGN KEY (PROMO_ID) REFERENCES PROMOIDS(ID)
    
) ;

CREATE TABLE CODES (
    ID INT NOT NULL AUTO_INCREMENT,
    ARTIST_ID INT NOT NULL,
    ALBUM_ID INT NOT NULL,
    CODE varchar(9) NOT NULL,

    PRIMARY KEY(ID),

    FOREIGN KEY (ARTIST_ID)
      REFERENCES ARTISTS(ID),

    FOREIGN KEY (ALBUM_ID)
      REFERENCES ALBUMS(ID)
) ;

INSERT INTO ARTISTS (NAME) VALUES ("Elton John");
INSERT INTO ARTISTS (NAME) VALUES ("Frank Turner");
INSERT INTO ARTISTS (NAME) VALUES ("Eric Clapton");


INSERT INTO PROMOIDS (NAME, PID) VALUES ("Back To Black", 737);
INSERT INTO PROMOIDS (NAME, PID) VALUES ("Sound of Vinyl", 755);
INSERT INTO PROMOIDS (NAME, PID) VALUES ("U2 Redemption", 790);

INSERT ALBUMS (NAME, PIGID, ARTIST_ID, PROMO_ID) VALUES ("17-11-70+", 1111, (SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"), (SELECT ID FROM promoids WHERE PID = 737));
INSERT ALBUMS (NAME, PIGID, ARTIST_ID, PROMO_ID) VALUES ("17-11-70+", 2222, (SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"), (SELECT ID FROM promoids WHERE PID = 755));
INSERT ALBUMS (NAME, PIGID, ARTIST_ID, PROMO_ID) VALUES ("Positive Songs for Negative People", 3333, (SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"), (SELECT ID FROM promoids WHERE PID = 755));
INSERT ALBUMS (NAME, PIGID, ARTIST_ID, PROMO_ID) VALUES ("The Studio Album Collection", 4444, (SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"), (SELECT ID FROM promoids WHERE PID = 790));

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA1", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+" AND PROMO_ID = 1)
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA2", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+" AND PROMO_ID = 1)
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA3", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+" AND PROMO_ID = 1)
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA4", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+" AND PROMO_ID = 1)
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA5", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+" AND PROMO_ID = 2)
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA6", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+" AND PROMO_ID = 2)
    ) ;



INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB1", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;
    
INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB2", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB3", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB4", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB5", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB6", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB7", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;


    
    


INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC1", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;
    
INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC2", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC3", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC4", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC5", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC6", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC7", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

