DROP DATABASE IF EXISTS coderedemp;
CREATE DATABASE IF NOT EXISTS coderedemp;

USE coderedemp;

DROP TABLE IF EXISTS ARTISTS;
DROP TABLE IF EXISTS ALBUMS;
DROP TABLE IF EXISTS CODES;



CREATE TABLE ARTISTS ( 
  ID INT NOT NULL AUTO_INCREMENT, 
  NAME VARCHAR(50),
  PRIMARY KEY(ID)
) ;
  

CREATE TABLE ALBUMS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50),
    ARTIST_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ID)
    
) ;

CREATE TABLE CODES (
    ID INT NOT NULL AUTO_INCREMENT,
    ARTIST_ID INT NOT NULL,
    ALBUM_ID INT NOT NULL,
    CODE varchar(9) NOT NULL,

    PRIMARY KEY(ID),

    FOREIGN KEY (ARTIST_ID)
      REFERENCES ARTISTS(ID),

    FOREIGN KEY (ALBUM_ID)
      REFERENCES ALBUMS(ID)
) ;

INSERT INTO ARTISTS (NAME) VALUES ("Elton John");
INSERT INTO ARTISTS (NAME) VALUES ("Frank Turner");
INSERT INTO ARTISTS (NAME) VALUES ("Eric Clapton");

INSERT ALBUMS (NAME, ARTIST_ID) VALUES ("17-11-70+", (SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"));
INSERT ALBUMS (NAME, ARTIST_ID) VALUES ("Positive Songs for Negative People", (SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"));
INSERT ALBUMS (NAME, ARTIST_ID) VALUES ("The Studio Album Collection", (SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"));

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA1", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA2", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA3", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA4", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA5", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("AAAAAAAA6", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "ELTON JOHN"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "17-11-70+")
    ) ;



INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB1", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;
    
INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB2", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB3", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB4", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB5", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB6", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("BBBBBBBB7", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Frank Turner"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "Positive Songs for Negative People")
    ) ;


    
    


INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC1", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;
    
INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC2", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC3", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC4", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC5", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC6", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

INSERT INTO CODES (CODE, ARTIST_ID, ALBUM_ID) VALUES ("CCCCCCCC7", 
	(SELECT ID FROM ARTISTS WHERE NAME LIKE  "Eric Clapton"),
    (SELECT ID FROM ALBUMS WHERE NAME LIKE  "The Studio Album Collection")
    ) ;

